spring:
  application:
    name: mercury-order-service

  datasource:
    username: order_service
    password: orderpass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    user: flyway_user
    password: flywaypass
    schemas: mercury
    default-schema: mercury
    table: flyway_orders_history
    baseline-on-migrate: true
    # IMPORTANT: orders should only see orders migrations
    locations: classpath:db/migration/orders

logging:
  level:
    root: INFO
    org.flywaydb: INFO
    org.springframework.boot.autoconfigure.flyway: INFO
    com.zaxxer.hikari: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      # optional but recommended:
      slo:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s,2s,5s
    tags:
      application: ${spring.application.name}